apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: eferhatg/cas-server
      context: server
      docker:
        dockerfile: Dockerfile
      sync:
        "server/*": .
    - image: eferhatg/cache-server
      context: cacheserver
      docker:
        dockerfile: Dockerfile
      sync:
        "cacheserver/*": .

deploy:
  kubectl:
    manifests:
      - k8s/server-deployment.yml
      - k8s/cache-deployment.yml
      - k8s/ingress-service.yml
