apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: eferhatg/cas-server
      context: server
      docker:
        dockerfile: Dockerfile
      sync:
        "server/*": .
    - image: eferhatg/cas-cache
      context: cacheserver
      docker:
        dockerfile: Dockerfile
      sync:
        "cacheserver/*": .
    - image: eferhatg/cas-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        "client/*": .

deploy:
  kubectl:
    manifests:
      - k8s/server-deployment.yml
      - k8s/cache-deployment.yml
      - k8s/ingress-service.yml
      - k8s/service-monitor.yml
      - k8s/client-deployment.yml
